# Site settings
title: Roowilliams
email: roo@roowilliams.com
description: > # this means to ignore newlines until "baseurl:"
Roo Williams: Design Technologist & Maker
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://roowilliams.github.io" # the base hostname & protocol for your site
twitter_username: roowilliams
github_username:  roowilliams

# Build settings
markdown: kramdown

sass:
    sass_dir: css/_sass

collections:
  projects:
    output: true
  experiments:
    output: true

# Serving
port: 4000
host: 0.0.0.0

gems:
- jekyll-compass
